version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: library-mysql
    environment:
      MYSQL_DATABASE: library_db
      MYSQL_ROOT_PASSWORD: 20g21a0434_P
    ports:
      - "3307:3306"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/library_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 20g21a0434_P
    depends_on:
      - mysql
